import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const runbook = readFileSync(new URL('../docs/squad-mupot-cutover.md', import.meta.url), 'utf8')

describe('squad mupot cutover runbook', () => {
  it('does not describe wake-hook cutover as blocked by a missing inbox route', () => {
    expect(runbook).toContain('now that signed inbox exists')
    expect(runbook).toContain('gated by live host receipts, not by route availability')
    expect(runbook).toContain('/api/inbox/signed')
    expect(runbook).toContain('fleet-runtime/inbox-handler.mjs')
    expect(runbook).not.toContain('blocked on the HTTP inbox route')
    expect(runbook).not.toContain('once the HTTP inbox route exists')
  })

  it('keeps SOS wake-hook removal gated by the complete host evidence bundle', () => {
    expect(runbook).toContain('until the target host has a passing receipt bundle')
    expect(runbook).toContain('install.json')
    expect(runbook).toContain('probe-*.json')
    expect(runbook).toContain('runtime-<agent_id>.json')
    expect(runbook).toContain('control-*.json')
    expect(runbook).toContain('cutover-gate.json')
    expect(runbook).toContain('manifest.json')
    expect(runbook).toContain('manifest.json` and `cutover-gate.json` report `status:"pass"`')
    expect(runbook).toContain('--verify-only')
    expect(runbook).toContain('--status')
    expect(runbook).toContain('mupot-fleet-receipt-bundle-status/v1')
    expect(runbook).toContain('--export')
    expect(runbook).toContain('--export-dir')
    expect(runbook).toContain('npm run receipt:bundle:export')
    expect(runbook).toContain('mupot-fleet-receipt-bundle-export/v1')
    expect(runbook).toContain('copies only `manifest.json` plus')
    expect(runbook).toContain('--check-manifest')
    expect(runbook).toContain('mupot-fleet-receipt-bundle-check/v1')
    expect(runbook).toContain('receipt type/status metadata')
    expect(runbook).toContain('manifest summary/status')
    expect(runbook).toContain('host/probe/runtime/control/cutover-gate evidence')
    expect(runbook).toContain('cutover-gate inputs')
    expect(runbook).toContain('base URLs and tenants match')
    expect(runbook).toContain('rejects secret material')
    expect(runbook).toContain('rejects non-self-contained')
    expect(runbook).toContain('extra files')
    expect(runbook).toContain('contradictory `next_steps`')
    expect(runbook).toContain('SHA-256 hashes')
    expect(runbook).toContain('manifest.json.next_steps')
    expect(runbook).toContain('advisory `next_steps`')
  })
})
