import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const root = new URL('..', import.meta.url)
const read = (rel: string) => readFileSync(new URL(rel, root), 'utf8')

const adapter = read('scripts/runtime_adapter_v1.py')
const cursorWorker = read('scripts/cursor-worker.py')
const mumcpWorker = read('scripts/mumcp-worker.py')
const codexWorker = read('scripts/codex-worker.py')
const claudeCodeWorker = read('scripts/claude-code-worker.py')
const attachRoutes = read('src/fleet/attach-routes.ts')
const contractMd = read('docs/runtime-adapter-contract.md')
const codexToml = read('connectors/codex/config.toml')
const codexReadme = read('connectors/codex/README.md')
const claudeMcp = read('connectors/claude/.mcp.json')
const claudeReadme = read('connectors/claude/README.md')
const flockMcp = read('packs/claude-code/flock-agent/.mcp.json.template')

describe('runtime-adapter/v1 reference drivers (BYOA topology A)', () => {
  it('ships a shared reference adapter declaring the contract + signed attach domain', () => {
    expect(adapter).toContain('CONTRACT_ID = "runtime-adapter/v1"')
    expect(adapter).toContain('SIGNED_ATTACH_DOMAIN = "fleet-attach:v1"')
    expect(adapter).toContain('SIGNED_DETACH_DOMAIN = "fleet-detach:v1"')
    expect(adapter).toContain('SIGNED_INBOX_DOMAIN = "agent-inbox:v1"')
    expect(adapter).toContain('LAND_AT_STATUS = "review"')
    expect(adapter).toContain('ATTACH_SIGNED_PATH = "/api/fleet/attach-signed"')
    expect(adapter).toContain('ATTACH_PATH = "/api/fleet/attach"')
    expect(adapter).toContain('def resolve_identity(')
    expect(adapter).toContain('boot_context')
    expect(adapter).toContain('def signed_attach(')
    expect(adapter).toContain('def bearer_attach(')
    expect(adapter).toContain('def land_at_review(')
    expect(adapter).toContain('FORBIDDEN_ADAPTER_ACTIONS')
    expect(adapter).toContain('"merge"')
    expect(adapter).toContain('"deploy"')
    expect(adapter).toContain('"self_verdict"')
  })

  it('refactors cursor-worker onto the reference adapter with runtime=cursor', () => {
    expect(cursorWorker).toContain('from runtime_adapter_v1 import')
    expect(cursorWorker).toContain('CONTRACT_ID')
    expect(cursorWorker).toContain('SIGNED_ATTACH_DOMAIN')
    expect(cursorWorker).toContain('RUNTIME_TYPE = "cursor"')
    expect(cursorWorker).toContain('boot_session(')
    expect(cursorWorker).toContain('poll_open_tasks(')
    expect(cursorWorker).toContain('land_at_review(')
    expect(cursorWorker).toContain('claim_in_progress(')
    // Behavior rails preserved.
    expect(cursorWorker).toContain('worktree", "add"')
    expect(cursorWorker).toContain('npx", "tsc", "--noEmit"')
    expect(cursorWorker).toContain('gh", "pr", "create"')
    expect(cursorWorker).toContain('Do NOT push, do NOT open a PR')
    expect(cursorWorker).not.toContain('CURSOR_AGENT_ID')
    expect(cursorWorker).not.toContain('task_verdict')
    expect(cursorWorker).not.toMatch(/npm run deploy|gh pr merge/)
  })

  it('keeps own-assignee polling on the shared adapter (server-derived agent_id)', () => {
    expect(adapter).toContain('"assignee_agent_id": identity.agent_id')
    expect(adapter).toContain('Own-assignee filter')
  })

  it('refactors mumcp-worker onto the reference adapter with runtime=claude-code', () => {
    expect(mumcpWorker).toContain('from runtime_adapter_v1 import')
    expect(mumcpWorker).toContain('CONTRACT_ID')
    expect(mumcpWorker).toContain('SIGNED_ATTACH_DOMAIN')
    expect(mumcpWorker).toContain('RUNTIME_TYPE = "claude-code"')
    expect(mumcpWorker).toContain('boot_session(')
    expect(mumcpWorker).toContain('poll_open_tasks(')
    expect(mumcpWorker).toContain('land_at_review(')
    expect(mumcpWorker).toContain('MUMCP_RESULT')
    expect(mumcpWorker).toContain('draft_only')
    expect(mumcpWorker).toContain('Never publish')
    expect(mumcpWorker).not.toContain('MUMCP_AGENT_ID')
    expect(mumcpWorker).not.toContain('task_verdict')
    expect(mumcpWorker).not.toMatch(/npm run deploy|gh pr merge/)
  })

  it('ships codex-worker on the reference adapter with runtime=codex (BYOA slice 2)', () => {
    expect(codexWorker).toContain('from runtime_adapter_v1 import')
    expect(codexWorker).toContain('CONTRACT_ID')
    expect(codexWorker).toContain('SIGNED_ATTACH_DOMAIN')
    expect(codexWorker).toContain('RUNTIME_TYPE = "codex"')
    expect(codexWorker).toContain('boot_session(')
    expect(codexWorker).toContain('poll_open_tasks(')
    expect(codexWorker).toContain('land_at_review(')
    expect(codexWorker).toContain('claim_in_progress(')
    expect(codexWorker).toContain('"exec"')
    expect(codexWorker).toContain('"--sandbox"')
    expect(codexWorker).toContain('"--json"')
    expect(codexWorker).toContain('worktree", "add"')
    expect(codexWorker).toContain('npx", "tsc", "--noEmit"')
    expect(codexWorker).toContain('gh", "pr", "create"')
    expect(codexWorker).toContain('bearer_token_env_var')
    expect(codexWorker).toContain('run_mint_attach')
    expect(codexWorker).toContain('Do NOT push, do NOT open a PR')
    expect(codexWorker).not.toContain('CODEX_AGENT_ID')
    expect(codexWorker).not.toContain('task_verdict')
    expect(codexWorker).not.toMatch(/npm run deploy|gh pr merge/)
    expect(codexWorker).toContain('mcp_config_stanza')
    expect(codexWorker).toContain('streamable-HTTP')
  })

  it('wires Codex remote MCP as streamable-HTTP (url + bearer_token_env_var, no SSE)', () => {
    expect(codexToml).toContain('bearer_token_env_var')
    expect(codexToml).toContain('url = ')
    expect(codexToml).not.toMatch(/^type\s*=\s*"sse"/m)
    expect(codexToml).not.toMatch(/^transport\s*=\s*"sse"/m)
    expect(codexReadme).toContain('Streamable-HTTP')
    expect(codexReadme).toContain('bearer_token_env_var')
    expect(codexReadme).not.toMatch(/^type = "sse"$/m)
  })

  it('ships claude-code-worker on the reference adapter with runtime=claude-code (BYOA slice 3)', () => {
    expect(claudeCodeWorker).toContain('from runtime_adapter_v1 import')
    expect(claudeCodeWorker).toContain('CONTRACT_ID')
    expect(claudeCodeWorker).toContain('SIGNED_ATTACH_DOMAIN')
    expect(claudeCodeWorker).toContain('RUNTIME_TYPE = "claude-code"')
    expect(claudeCodeWorker).toContain('boot_session(')
    expect(claudeCodeWorker).toContain('poll_open_tasks(')
    expect(claudeCodeWorker).toContain('land_at_review(')
    expect(claudeCodeWorker).toContain('claim_in_progress(')
    expect(claudeCodeWorker).toContain('"-p"')
    expect(claudeCodeWorker).toContain('"--output-format"')
    expect(claudeCodeWorker).toContain('stream-json')
    expect(claudeCodeWorker).toContain('worktree", "add"')
    expect(claudeCodeWorker).toContain('npx", "tsc", "--noEmit"')
    expect(claudeCodeWorker).toContain('gh", "pr", "create"')
    expect(claudeCodeWorker).toContain('mcp_json_document')
    expect(claudeCodeWorker).toContain('"type": "http"')
    expect(claudeCodeWorker).toContain('headers.Authorization')
    expect(claudeCodeWorker).toContain('run_mint_attach')
    expect(claudeCodeWorker).toContain('Do NOT push, do NOT open a PR')
    expect(claudeCodeWorker).not.toContain('CLAUDE_CODE_AGENT_ID')
    expect(claudeCodeWorker).not.toContain('task_verdict')
    expect(claudeCodeWorker).not.toMatch(/npm run deploy|gh pr merge/)
  })

  it('wires Claude Code remote MCP as type:http (.mcp.json + headers.Authorization, no SSE)', () => {
    expect(claudeMcp).toContain('"type": "http"')
    expect(claudeMcp).toContain('"Authorization"')
    expect(claudeMcp).not.toContain('"type": "sse"')
    expect(flockMcp).toContain('"type": "http"')
    expect(flockMcp).toContain('"Authorization"')
    expect(flockMcp).not.toContain('"type": "sse"')
    expect(claudeReadme).toContain('type: "http"')
    expect(claudeReadme).toContain('claude-code-worker.py')
    expect(claudeReadme).toContain('stream-json')
  })

  it('accepts cursor, codex, and claude-code as declared attach runtime types on the pot', () => {
    expect(attachRoutes).toMatch(/VALID_RUNTIMES = new Set\(\[[\s\S]*'cursor'/)
    expect(attachRoutes).toMatch(/VALID_RUNTIMES = new Set\(\[[\s\S]*'codex'/)
    expect(attachRoutes).toMatch(/VALID_RUNTIMES = new Set\(\[[\s\S]*'claude-code'/)
    expect(contractMd).toContain('`cursor`')
    expect(contractMd).toContain('`codex`')
    expect(contractMd).toContain('`claude-code`')
  })

  it('keeps topology-A workers on the shared adapter (no bespoke glue outside the contract)', () => {
    expect(cursorWorker).toContain('runtime-adapter/v1')
    expect(mumcpWorker).toContain('runtime-adapter/v1')
    expect(codexWorker).toContain('runtime-adapter/v1')
    expect(claudeCodeWorker).toContain('runtime-adapter/v1')
    expect(adapter).toContain('REFERENCE adapter')
  })
})
