"""
mupot Hermes Plugin — tool implementations (v0.1).

v0.1 IS PLAN-ONLY for provisioning.  The apply path (confirm=True, dry_run=False)
requires an externally-constructed CloudflareClient — the real `cloudflare` SDK is NOT
bundled in v0.1.  Without an injected client, the tool returns a structured plan with
the exact wrangler CLI commands to run.  Real apply (auto-constructed SDK client) lands
in v0.2.

Risk annotations match the design doc (mupot-hermes-plugin-v0.1.md):
  Risk 1 — CF token on disk (least-scoped token; revoke after provision).
  Risk 2 — Migration drift landmine (DRY-RUN + explicit confirm required).
  Risk 3 — Brain token must be SCOPED, not mcp:*.  Plugin documents the requirement
            but CANNOT enforce token scope — the operator must supply a scoped token.
  Risk 4 — wrangler version drift (pin + check).
  Risk 5 — Workers free-tier slot warning.
"""

from __future__ import annotations

import json
import os
import re
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional, Protocol

# ── CF client protocol (injectable for tests / dry-run) ──────────────────────


class CloudflareClient(Protocol):
    """Minimal surface of the CF API used by the provisioner."""

    def list_d1_databases(self, account_id: str) -> list[dict[str, Any]]: ...
    def create_d1_database(self, account_id: str, name: str) -> dict[str, Any]: ...
    def list_kv_namespaces(self, account_id: str) -> list[dict[str, Any]]: ...
    def create_kv_namespace(self, account_id: str, title: str) -> dict[str, Any]: ...


@dataclass
class DryRunClient:
    """
    Stub CF client — records calls, never touches Cloudflare.
    Used when dry_run=True (default) or injected in tests.
    """

    calls: list[dict[str, Any]] = field(default_factory=list)
    _d1_db_counter: int = 0
    _kv_ns_counter: int = 0

    def list_d1_databases(self, account_id: str) -> list[dict[str, Any]]:
        self.calls.append({"method": "list_d1_databases", "account_id": account_id})
        return []  # default: nothing exists yet

    def create_d1_database(self, account_id: str, name: str) -> dict[str, Any]:
        self.calls.append(
            {"method": "create_d1_database", "account_id": account_id, "name": name}
        )
        self._d1_db_counter += 1
        return {"id": f"dry-run-d1-{self._d1_db_counter:04d}", "name": name}

    def list_kv_namespaces(self, account_id: str) -> list[dict[str, Any]]:
        self.calls.append(
            {"method": "list_kv_namespaces", "account_id": account_id}
        )
        return []

    def create_kv_namespace(self, account_id: str, title: str) -> dict[str, Any]:
        self.calls.append(
            {
                "method": "create_kv_namespace",
                "account_id": account_id,
                "title": title,
            }
        )
        self._kv_ns_counter += 1
        return {"id": f"dry-run-kv-{self._kv_ns_counter:04d}", "title": title}


# ── slug validation ───────────────────────────────────────────────────────────

_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,28}[a-z0-9]$")


def _validate_slug(slug: str) -> None:
    if not _SLUG_RE.match(slug):
        raise ValueError(
            f"Invalid slug {slug!r}. Must be 2–30 lowercase alphanumeric + hyphens, "
            "no leading/trailing hyphen."
        )


# ── wrangler.toml template ────────────────────────────────────────────────────

_WRANGLER_TOML_TEMPLATE = """\
# wrangler.{slug}.toml — GENERATED by mupot_provision v0.1
# DO NOT COMMIT with real IDs if this file is in a public repo.
# Treat cf_api_token as a secret: set via `wrangler secret put` or env, never here.
name = "mupot-{slug}"
main = "src/index.ts"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]

[vars]
TENANT_SLUG = "{slug}"
BRAND = "{brand}"
OAUTH_PROVIDER = "{oauth_provider}"
FLEET_PROJECT = "sos"
FLEET_OPS_AGENT = "kasra"

[[d1_databases]]
binding = "DB"
database_name = "mupot-{slug}"
database_id = "{d1_id}"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "SESSIONS"
id = "{sessions_kv_id}"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "{oauth_kv_id}"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "AGENT"
class_name = "AgentDO"

[[durable_objects.bindings]]
name = "SQUAD"
class_name = "SquadCoordinatorDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AgentDO", "SquadCoordinatorDO"]

[[workflows]]
name = "mupot-task-workflow"
binding = "TASK_WORKFLOW"
class_name = "TaskWorkflow"

[triggers]
crons = ["*/15 * * * *"]
"""


# ── mupot_provision ──────────────────────────────────────────────────────────


def mupot_provision(
    slug: str,
    brand: str,
    cf_account_id: str,
    cf_api_token: str,
    oauth_provider: str = "google",
    confirm: bool = False,
    dry_run: bool = True,
    *,
    cf_client: Optional[CloudflareClient] = None,
    toml_output_dir: Optional[Path] = None,
) -> dict[str, Any]:
    """
    Idempotent mupot provisioner.

    Phase 1 (always): list-guard check existing CF resources, build a plan.
    Phase 2 (only if confirm=True AND dry_run=False): create resources + write toml.
    Migration apply is NEVER done here — emitted as next_steps only (Risk 2).

    Returns a structured plan/result dict.
    """
    _validate_slug(slug)

    # dry_run flag takes precedence over confirm as a safety guard
    applying = confirm and not dry_run

    # Use stub client if dry-running or no real client provided
    client: CloudflareClient
    if cf_client is not None:
        client = cf_client
    elif not applying:
        client = DryRunClient()
    else:
        # v0.1 does NOT bundle the cloudflare SDK — it cannot construct a real client.
        # Return an honest plan-only response with the exact CLI commands to run.
        # Real SDK-backed apply lands in v0.2.
        _validate_slug(slug)
        worker_name = f"mupot-{slug}"
        return {
            "dry_run": True,
            "plan_only": True,
            "slug": slug,
            "worker_name": worker_name,
            "applied": False,
            "toml_path": None,
            "plan": [
                f"[v0.1 PLAN-ONLY] v0.1 cannot create real Cloudflare resources — "
                "no SDK client is bundled. Run the commands in next_steps yourself, "
                "or wait for v0.2 which wires the real Cloudflare client.",
            ],
            "next_steps": [
                "v0.1 is PLAN-ONLY. To provision your mupot instance, run these "
                "wrangler commands manually (or with automation):",
                f"1. Create D1 database:\n"
                f"   npx wrangler d1 create mupot-{slug}",
                f"2. Create KV namespaces:\n"
                f"   npx wrangler kv namespace create mupot-{slug}-sessions\n"
                f"   npx wrangler kv namespace create mupot-{slug}-oauth",
                f"3. Copy wrangler.example.toml → wrangler.{slug}.toml and fill in "
                "the D1 database_id and KV namespace IDs from the output above.",
                f"4. Deploy the worker:\n"
                f"   npx wrangler deploy --config wrangler.{slug}.toml",
                "5. MIGRATION — always dry-run first (Risk 2):\n"
                f"   npx wrangler d1 migrations apply mupot-{slug} --dry-run "
                f"--config wrangler.{slug}.toml\n"
                "   Review output. Only apply without --dry-run after confirming no "
                "destructive operations.",
                "6. Set OAuth secrets:\n"
                f"   npx wrangler secret put OAUTH_CLIENT_ID --config wrangler.{slug}.toml\n"
                f"   npx wrangler secret put OAUTH_CLIENT_SECRET --config wrangler.{slug}.toml",
                f"7. Verify: mupot_status(url='https://mupot-{slug}.workers.dev')",
                "v0.2 will wire the real Cloudflare SDK client so this tool executes "
                "steps 1-3 automatically. Track: https://github.com/Mumega-com/mupot/issues",
            ],
            "warnings": [
                "v0.1 is PLAN-ONLY. confirm=True + dry_run=False without an injected "
                "cf_client returns this plan, not a live apply. Real apply = v0.2.",
                "Each mupot pot consumes one Workers slot. "
                "Free tier = 100 slots. Check your usage before provisioning many pots.",
            ],
        }

    worker_name = f"mupot-{slug}"
    d1_name = f"mupot-{slug}"
    sessions_title = f"mupot-{slug}-sessions"
    oauth_title = f"mupot-{slug}-oauth"

    # ── idempotent list-guard ────────────────────────────────────────────────
    existing_d1 = client.list_d1_databases(cf_account_id)
    existing_kv = client.list_kv_namespaces(cf_account_id)

    existing_d1_ids = {db["name"]: db["id"] for db in existing_d1}
    existing_kv_ids = {ns["title"]: ns["id"] for ns in existing_kv}

    d1_exists = d1_name in existing_d1_ids
    sessions_exists = sessions_title in existing_kv_ids
    oauth_exists = oauth_title in existing_kv_ids

    plan: list[str] = []
    if d1_exists:
        plan.append(f"[SKIP] D1 database '{d1_name}' already exists — no-op.")
    else:
        plan.append(f"[CREATE] D1 database '{d1_name}'")

    if sessions_exists:
        plan.append(f"[SKIP] KV namespace '{sessions_title}' already exists — no-op.")
    else:
        plan.append(f"[CREATE] KV namespace '{sessions_title}'")

    if oauth_exists:
        plan.append(f"[SKIP] KV namespace '{oauth_title}' already exists — no-op.")
    else:
        plan.append(f"[CREATE] KV namespace '{oauth_title}'")

    result: dict[str, Any] = {
        "dry_run": not applying,
        "slug": slug,
        "worker_name": worker_name,
        "plan": plan,
        "applied": False,
        "toml_path": None,
        "next_steps": [],
        "warnings": [],
    }

    # ── Risk 5: Workers slot warning ─────────────────────────────────────────
    result["warnings"].append(
        "Each mupot pot consumes one Workers slot. "
        "Free tier = 100 slots. Check your usage before provisioning many pots."
    )

    if not applying:
        result["next_steps"] = [
            "v0.1 is PLAN-ONLY — this tool does NOT create resources and confirm does "
            "NOT apply (no Cloudflare SDK is bundled in v0.1). Run these wrangler "
            "commands manually to provision (v0.2 will wire the SDK to run them):",
            f"1. npx wrangler d1 create mupot-{slug}",
            f"2. npx wrangler kv namespace create mupot-{slug}-sessions  &&  "
            f"npx wrangler kv namespace create mupot-{slug}-oauth",
            f"3. Copy wrangler.example.toml → wrangler.{slug}.toml; fill in the D1 "
            f"database_id + KV namespace IDs from the output above.",
            f"4. npx wrangler deploy --config wrangler.{slug}.toml",
            f"5. MIGRATION — dry-run FIRST (Risk 2 drift landmine): npx wrangler d1 "
            f"migrations apply mupot-{slug} --dry-run --config wrangler.{slug}.toml ; "
            "apply only after reviewing output for destructive ops.",
            f"6. npx wrangler secret put OAUTH_CLIENT_ID (then OAUTH_CLIENT_SECRET) "
            f"--config wrangler.{slug}.toml (Risk 1: least-scoped token).",
            f"7. mupot_status(url='https://mupot-{slug}.workers.dev') to verify.",
            "8. Optionally mupot_brain_enable to wire the DMN brain.",
        ]
        return result

    # ── Apply phase ──────────────────────────────────────────────────────────
    d1_id = (
        existing_d1_ids[d1_name]
        if d1_exists
        else client.create_d1_database(cf_account_id, d1_name)["id"]
    )
    sessions_kv_id = (
        existing_kv_ids[sessions_title]
        if sessions_exists
        else client.create_kv_namespace(cf_account_id, sessions_title)["id"]
    )
    oauth_kv_id = (
        existing_kv_ids[oauth_title]
        if oauth_exists
        else client.create_kv_namespace(cf_account_id, oauth_title)["id"]
    )

    toml_content = _WRANGLER_TOML_TEMPLATE.format(
        slug=slug,
        brand=brand,
        oauth_provider=oauth_provider,
        d1_id=d1_id,
        sessions_kv_id=sessions_kv_id,
        oauth_kv_id=oauth_kv_id,
    )

    out_dir = toml_output_dir or Path(".")
    toml_path = out_dir / f"wrangler.{slug}.toml"
    toml_path.write_text(toml_content, encoding="utf-8")

    result["applied"] = True
    result["toml_path"] = str(toml_path)
    result["d1_id"] = d1_id
    result["sessions_kv_id"] = sessions_kv_id
    result["oauth_kv_id"] = oauth_kv_id
    result["next_steps"] = [
        f"1. Deploy the worker: `npx wrangler deploy --config {toml_path}`",
        "2. MIGRATION — DRY-RUN FIRST (Risk 2):\n"
        f"   npx wrangler d1 migrations apply mupot-{slug} --dry-run --config {toml_path}\n"
        "   Review the output. Only run WITHOUT --dry-run after confirming no destructive ops.",
        "3. Set secrets:\n"
        f"   npx wrangler secret put OAUTH_CLIENT_ID --config {toml_path}\n"
        f"   npx wrangler secret put OAUTH_CLIENT_SECRET --config {toml_path}",
        f"4. Test: mupot_status(url='https://mupot-{slug}.workers.dev')",
        "5. Optionally: mupot_brain_enable(slug=...) to wire the DMN brain.",
        "6. After provision, consider revoking the CF token or reducing its scope (Risk 1).",
    ]
    return result


# ── mupot_status ─────────────────────────────────────────────────────────────


def mupot_status(
    url: str,
    *,
    http_fetch: Optional[Any] = None,
) -> dict[str, Any]:
    """
    Probe a live mupot deployment's /health endpoint.

    http_fetch: injectable callable(url: str) -> Response-like with .status_code + .json().
    If not provided and _ALLOW_REAL_HTTP is False, returns a dry-run result.
    """
    # Normalise trailing slash
    base = url.rstrip("/")
    health_url = f"{base}/health"

    if http_fetch is None:
        # Guard: no real HTTP in test/CI unless explicitly provided
        return {
            "dry_run": True,
            "ok": None,
            "url": base,
            "health_url": health_url,
            "message": (
                "No http_fetch injected. Pass http_fetch=requests.get (or a mock) "
                "to probe a live deployment."
            ),
        }

    try:
        resp = http_fetch(health_url)
        if resp.status_code == 200:
            data = resp.json()
            return {
                "dry_run": False,
                "ok": True,
                "url": base,
                "health_url": health_url,
                "tenant": data.get("tenant"),
                "raw": data,
            }
        return {
            "dry_run": False,
            "ok": False,
            "url": base,
            "health_url": health_url,
            "status_code": resp.status_code,
            "message": f"Health endpoint returned {resp.status_code}.",
        }
    except Exception as exc:  # noqa: BLE001
        return {
            "dry_run": False,
            "ok": False,
            "url": base,
            "health_url": health_url,
            "error": str(exc),
        }


# ── mupot_brain_enable ───────────────────────────────────────────────────────

_BRAIN_CONFIG_TEMPLATE = """\
# Hermes profile config — mupot-{slug} brain (DMN prioritizer)
# Model: qwen/qwen3.7-plus via OpenRouter — cheap, fast, adequate for ranking.
# Generated by mupot_brain_enable v0.1.
#
# INSTALL STEPS (emitted by mupot_brain_enable — execute manually or via automation):
#   See next_steps in the tool output.

model:
  default: qwen/qwen3.7-plus
  provider: openrouter
  base_url: https://openrouter.ai/api/v1
  api_mode: chat_completions

providers: {{}}
fallback_providers: []

toolsets:
  - hermes-cli

agent:
  max_turns: 12
  gateway_timeout: 300
  restart_drain_timeout: 30
  api_max_retries: 2
  tool_use_enforcement: auto
  reasoning_effort: low
  verbose: false

terminal:
  backend: local
  timeout: 60
  auto_source_bashrc: true
  persistent_shell: false

web:
  backend: ''
  search_backend: ''
  extract_backend: ''
"""

_CRON_SCRIPT_TEMPLATE = """\
#!/usr/bin/env python3
# mupot-{slug}-brain cron — DMN priority scan, every 15 minutes.
# REAL FILE (not symlink) — required so Hermes cron scheduler can read it directly.
# See: feedback_cron_scheduled_neq_running.md — symlinks cause silent cron failures.
#
# This script is the entrypoint for the mupot-{slug} brain's priority scan.
# It calls the brain profile's prioritize_scan logic with the pot's token.
#
# TOKEN SCOPE NOTE (Risk 3): This script checks that TOKEN_ENV is SET, but it
# CANNOT verify the token's scope — token introspection is not available here.
# The OPERATOR must supply a scoped token (task:read + priority:write only).
# Using mcp:* would grant full bus control to this always-on automated agent.
# Scope enforcement is the operator's responsibility — not this script's.

import os
import subprocess
import sys

SLUG = "{slug}"
HERMES_HOME = os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes"))
TOKEN_ENV = "MUMEGA_BRAIN_TOKEN_{slug_upper}"

def main() -> None:
    token = os.environ.get(TOKEN_ENV)
    if not token:
        print(
            f"[mupot-brain-cron] {{TOKEN_ENV}} not set. "
            "Operator must supply a SCOPED token (task:read + priority:write). "
            "NOT mcp:* — see Risk 3 in mupot-hermes-plugin-v0.1.md. "
            "Note: this script can only check the token EXISTS, not its scope.",
            file=sys.stderr,
        )
        sys.exit(1)

    profile_dir = os.path.join(
        HERMES_HOME, "profiles", f"mupot-{{SLUG}}-brain"
    )
    scan_script = os.path.join(
        HERMES_HOME, "scripts", f"mupot_{{SLUG}}_brain_scan.py"
    )

    if not os.path.isfile(scan_script):
        print(
            f"[mupot-brain-cron] Scan script not found: {{scan_script}}. "
            "Copy from Mumega-com/mupot-plugin/brain/prioritize_scan.py.",
            file=sys.stderr,
        )
        sys.exit(1)

    subprocess.run(
        [sys.executable, scan_script, "--profile", profile_dir, "--dry-run"],
        check=True,
        env={{**os.environ, TOKEN_ENV: token}},
    )


if __name__ == "__main__":
    main()
"""


def mupot_brain_enable(
    slug: str,
    hermes_home: str = "~/.hermes",
    openrouter_api_key_env: str = "OPENROUTER_API_KEY",
) -> dict[str, Any]:
    """
    Emit the plan + commands to wire the DMN brain for a provisioned mupot pot.

    v0.1: returns a structured plan dict. Does NOT execute against a live host.
    The caller (Hermes agent or human operator) follows the next_steps.

    Risk 3: the plan DOCUMENTS that the operator must supply a SCOPED token (task:read +
    priority:write), NOT mcp:*. The plugin does NOT enforce token scope — no bus
    introspection is available in the cron context; scope is the operator's responsibility.
    """
    _validate_slug(slug)
    slug_upper = slug.upper().replace("-", "_")

    home = hermes_home.rstrip("/")
    profile_dir = f"{home}/profiles/mupot-{slug}-brain"
    scripts_dir = f"{home}/scripts"
    cron_script_path = f"{scripts_dir}/mupot_{slug}_cron.py"  # REAL FILE, not symlink
    cron_jobs_path = f"{home}/cron/jobs.json"
    config_path = f"{profile_dir}/config.yaml"
    token_env_var = f"MUMEGA_BRAIN_TOKEN_{slug_upper}"

    config_content = _BRAIN_CONFIG_TEMPLATE.format(slug=slug)
    cron_script_content = _CRON_SCRIPT_TEMPLATE.format(
        slug=slug, slug_upper=slug_upper
    )

    cron_entry = {
        "name": f"mupot-{slug}-brain-scan",
        "schedule": "*/15 * * * *",
        "command": f"python3 {cron_script_path}",
        "profile": f"mupot-{slug}-brain",
        "enabled": True,
    }

    next_steps = [
        f"1. Create profile directory:\n   mkdir -p {profile_dir}",
        f"2. Write config.yaml to {config_path}\n"
        f"   (content emitted in this result under 'config_yaml')",
        f"3. Write the cron script as a REAL FILE (NOT a symlink — Risk: symlinks "
        f"cause silent Hermes cron failures):\n"
        f"   {cron_script_path}\n"
        f"   (content emitted in this result under 'cron_script')",
        f"4. chmod +x {cron_script_path}",
        f"5. Register the cron entry in {cron_jobs_path}.\n"
        f"   Hermes hotloads cron config without daemon restart.\n"
        f"   Entry to add (emitted under 'cron_entry').",
        f"6. Set a SCOPED brain token (Risk 3 — NOT mcp:*):\n"
        f"   OPERATOR RESPONSIBILITY: supply a token scoped to task:read + priority:write.\n"
        f"   The plugin documents this requirement but cannot enforce token scope.\n"
        f"   Export: export {token_env_var}=<scoped-token>\n"
        f"   Or add to ~/.env.secrets: {token_env_var}=<scoped-token>",
        f"7. Set {openrouter_api_key_env} in your environment for qwen3.7-plus.",
        f"8. Verify dry-run:\n"
        f"   python3 {cron_script_path} --dry-run",
        f"9. Hermes will pick up the cron within one poll cycle (~60s). "
        f"Watch the first scan: `hermes logs --profile mupot-{slug}-brain`",
    ]

    warnings = [
        f"Risk 3 (token scope — operator responsibility): {token_env_var} MUST be a "
        "scoped token (task:read + priority:write). mcp:* would grant full bus control "
        "to an always-on automated agent — never do this. "
        "The plugin DOCUMENTS this requirement but CANNOT enforce token scope — "
        "the Mumega bus does not expose token introspection to this cron script.",
        "Cron script MUST be a real file, not a symlink. Hermes cron scheduler reads "
        "the script path directly; a broken symlink causes a silent non-execution.",
        f"The brain profile uses qwen/qwen3.7-plus via OpenRouter. "
        f"Ensure {openrouter_api_key_env} is set with sufficient quota.",
    ]

    return {
        "dry_run": True,  # v0.1 always emits a plan, never executes
        "slug": slug,
        "profile_dir": profile_dir,
        "cron_script_path": cron_script_path,
        "token_env_var": token_env_var,
        "config_yaml": config_content,
        "cron_script": cron_script_content,
        "cron_entry": cron_entry,
        "next_steps": next_steps,
        "warnings": warnings,
    }
