// mupot — fleet → GitHub agent-def sync (C4 + C5).
//
// Turns the pot's own agent roster into GitHub coding-agent definitions: for each active
// agent we generate a `.github/agents/<slug>.agent.md` and write it via the gated
// writeAgentDef. Each generated def wires its `mcp-servers` at THIS pot's MCP endpoint
// (C5), so the GitHub cloud agent reads the pot's own bus / memory / tasks — the agent on
// GitHub is the same agent that lives in the pot.
//
// The MCP token is referenced as ${COPILOT_MCP_MUPOT_TOKEN}, a repo secret the operator sets
// (never embedded). Generation is pure + tested; the write reuses the adversarial-reviewed
// writeAgentDef (capability-gated, fail-closed, no path traversal).

import type { Env } from '../types'
import { writeAgentDef, isValidAgentName, type WriteAgentDefResult } from './github-repo-write'

/** The slice of an agent row this generator needs. */
export interface FleetAgent {
  slug: string
  name: string
  role: string | null
  okr: string | null
  status: string
}

// YAML double-quoted scalar escape. Escapes backslash + double-quote, and flattens any
// CR/LF/tab to a space so a field value can never inject a new frontmatter line/key.
function yamlStr(s: string): string {
  return `"${s.replace(/[\r\n\t]+/g, ' ').replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

/** Derive a valid agent-def filename slug from an agent slug (sanitize to [a-z0-9-]). */
export function defSlug(agentSlug: string): string {
  return agentSlug
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40)
}

/**
 * Render a `.agent.md` for one agent, wiring its MCP at this pot's endpoint (C5).
 * Pure — `mcpUrl` is the resolved pot MCP endpoint (e.g. https://pot.example/mcp).
 */
export function agentDefMarkdown(agent: FleetAgent, mcpUrl: string): string {
  // Flatten CR/LF/tab in all free-text fields up front so neither the YAML frontmatter nor
  // the markdown body can have a value split across lines (frontmatter-key injection guard).
  const flat = (s: string) => s.replace(/[\r\n\t]+/g, ' ').trim()
  const name = flat(agent.name || '') || agent.slug
  const role = flat(agent.role || '') || 'pot agent'
  const okr = agent.okr ? flat(agent.okr) : ''
  const description =
    `${name} — ${role}. Backed by the mupot pot; reads the pot's bus, memory, and tasks via MCP.`

  const frontmatter = [
    '---',
    `name: ${yamlStr(name)}`,
    `description: ${yamlStr(description)}`,
    'tools:',
    '  - code_search',
    '  - file_edit',
    '  - terminal',
    '  - github',
    'mcp-servers:',
    '  mupot:',
    '    type: http',
    `    url: ${yamlStr(mcpUrl)}`,
    '    headers:',
    '      Authorization: "Bearer ${COPILOT_MCP_MUPOT_TOKEN}"',
    '---',
  ].join('\n')

  const body = [
    '',
    `## ${name}`,
    '',
    description,
    '',
    ...(okr ? [`**Objective:** ${okr}`, ''] : []),
    '## How you work',
    '',
    "- You are the GitHub-side presence of this pot agent. Use the `mupot` MCP server to read",
    '  your tasks, the pot bus, and shared memory before acting.',
    '- Implement, test, and open a PR. Do not merge — a human (or the pot review gate) approves.',
    '- Follow the repository conventions and keep changes scoped to the issue.',
    '',
    '_Generated by mupot fleet→GitHub sync. Edit the agent in the pot, not here — re-sync overwrites._',
    '',
  ].join('\n')

  return frontmatter + '\n' + body
}

export interface FleetSyncItem {
  agent: string
  ok: boolean
  detail: string
}

/**
 * Sync every active agent to `.github/agents/<slug>.agent.md` in `repo`, wiring MCP at
 * `mcpUrl`. Returns a per-agent result list. `dryRun` generates + validates without writing
 * (so an operator can preview). Skips agents whose slug can't form a valid def name.
 */
export async function syncFleetToGitHub(
  env: Env,
  params: { repo: string; mcpUrl: string; dryRun?: boolean },
  opts: { fetchImpl?: typeof fetch } = {},
): Promise<{ synced: number; items: FleetSyncItem[] }> {
  const rows = await env.DB.prepare(
    `SELECT slug, name, role, okr, status FROM agents WHERE status = 'active' ORDER BY slug ASC`,
  ).all<FleetAgent>()
  const agents = rows.results ?? []

  const items: FleetSyncItem[] = []
  let synced = 0
  for (const agent of agents) {
    const slug = defSlug(agent.slug)
    if (!isValidAgentName(slug)) {
      items.push({ agent: agent.slug, ok: false, detail: 'invalid_slug' })
      continue
    }
    const content = agentDefMarkdown(agent, params.mcpUrl)
    if (params.dryRun) {
      items.push({ agent: slug, ok: true, detail: `dry-run (${content.length} bytes)` })
      synced++
      continue
    }
    const res: WriteAgentDefResult = await writeAgentDef(
      env,
      { repo: params.repo, agentName: slug, content },
      opts.fetchImpl ? { fetchImpl: opts.fetchImpl } : {},
    )
    if (res.ok) {
      synced++
      items.push({ agent: slug, ok: true, detail: res.updated ? 'updated' : 'created' })
    } else {
      items.push({ agent: slug, ok: false, detail: res.error })
    }
  }
  return { synced, items }
}
