// mupot — every binding name the worker itself owns or reads, refused by the secret-env taker.
//
// WHY: RESERVED_BINDING_NAMES (names.ts) is a hand-kept denylist and was found
// incomplete (STRIPE_SECRET_KEY, TELEGRAM_BOT_TOKEN, ... were requestable). This list is
// the defense-in-depth layer: EVERY key the `Env` interface (src/types.ts) declares,
// plus the env.X names the source reads that the interface omits (optional secrets read
// through casts). A name here can never be requested through secret_env_request, so a
// stranger/agent cannot squat it and an admin approval can never overwrite it.
//
// RATCHET: tests/secret-env-env-names-ratchet.test.ts parses src/types.ts (TypeScript
// compiler API), every `*Env`/`*Secrets` interface in src/, template-literal name prefixes,
// and scans src/ for env.X / accessor(env).X / (env as T).X reads; it FAILS when a new Env key or env.X read
// is not in this list. Adding a key here is the review step: a name is only ever removed
// from the refusal set on purpose, never by omission.

export const ENV_REVIEWED_BINDING_NAMES: ReadonlySet<string> = new Set([
  'AGENT',
  'AGENT_COMMIT_EMAIL_DOMAIN',
  'AI',
  'AI_GATEWAY_TOKEN',
  'BILLING_PLAN_SECRET',
  'BLOBS',
  'BOOTSTRAP_OWNER_TOKEN',
  'BRAND',
  'BUS',
  'BUS_TOKEN',
  'BUS_URL',
  'CC_SPEND_SECRET',
  'CONNECTOR_MASTER_KEY',
  'CONSOLE_SWITCH_POT_URL',
  'CURSOR_API_KEY',
  'CURSOR_API_TOKEN',
  'DB',
  'DEFAULT_CPU_MS',
  'DEFAULT_POT_HOST_SUFFIX',
  'DEFAULT_SUBREQUESTS',
  'DISCORD_ADMIN_AGENT',
  'DISCORD_ADMIN_BOT_TOKEN',
  'DISCORD_BOT_TOKEN',
  'DISCORD_PUBLIC_KEY',
  'DISPATCHER',
  'EMAIL_LOGIN_ENABLED',
  'EMAIL_PROVIDER',
  'EVENTS_ENABLED',
  'EVENT_INGEST_SECRET',
  'EXEC_MAX_DISPATCH_DAY',
  'EXEC_MAX_TOKENS_DAY',
  'FLEET_CONSUMER_AGENT',
  'FLEET_OPS_AGENT',
  'FLEET_PANEL_SK',
  'FLEET_PRESENCE_TTL_SEC',
  'FLEET_PROJECT',
  'GHL_API_KEY',
  'GHL_INBOUND_SQUAD_ID',
  'GHL_LOCATION_ID',
  'GHL_WEBHOOK_SECRET',
  'GITHUB_APP_ID',
  'GITHUB_APP_INSTALLATION_ID',
  'GITHUB_APP_PRIVATE_KEY',
  'GITHUB_ENTERPRISE_FEATURES',
  'GITHUB_INBOUND_SQUAD_ID',
  'GITHUB_LABEL_SQUAD_MAP',
  'GITHUB_PLAN_TIER',
  'GITHUB_REPO',
  'GITHUB_SYNC_PROJECT',
  'GITHUB_TOKEN',
  'GITHUB_WEBHOOK_SECRET',
  'GOOGLE_CHAT_PROJECT_NUMBER',
  'GOOGLE_CHAT_SA_KEY',
  'GOOGLE_CHAT_VERIFY_TOKEN',
  'GOOGLE_CLIENT_ID',
  'GOOGLE_CLIENT_SECRET',
  'GOOGLE_WORKSPACE_DRIVE_ROOT',
  'HERMES_EVENTS_WEBHOOK_URL',
  'HERMES_RELAY_SECRET',
  'HERMES_WEBHOOK_SECRET',
  'IDP_PROVIDER',
  'IM_WEBHOOK_SECRET',
  'INKWELL_API_TOKEN',
  'INKWELL_API_URL',
  'INKWELL_SECRET',
  'INKWELL_SVC',
  'INKWELL_TOKEN',
  'LOCAL_TEST_AUTH',
  'LOCAL_TEST_AUTH_EMAIL',
  'MEMBER_TOKEN_FINGERPRINT_SECRET',
  'MIRROR_SECRET',
  'MIRROR_TOKEN',
  'MIRROR_URL',
  'MUPOT_HANDOFF_AUD',
  'MUPOT_HANDOFF_ISS',
  'MUPOT_HANDOFF_PUBLIC_KEY',
  'OAUTH_CLIENT_ID',
  'OAUTH_CLIENT_SECRET',
  'OAUTH_KV',
  'OAUTH_PROVIDER',
  'OWNER_TENANT_SLUG',
  'POSTHOG_HOST',
  'POSTHOG_PERSONAL_API_KEY',
  'POSTHOG_PROJECT_ID',
  'POT_SELF_SERVE_CHECKOUT_ENABLED',
  'POT_WORKER_BUNDLE_BUCKET',
  'PRESENCE_CHANNEL',
  'PROJECT_LINK_SIGNING_KEY',
  'PUBLIC_ORIGIN',
  'REALTIME_PRESENCE',
  'REALTIME_SEAT_EVENTS',
  'RELEASE_SHA',
  'RESEND_API_KEY',
  'RESEND_FROM_EMAIL',
  'ROOT_DOMAIN',
  'SEAT_EVENTS',
  'SECRET_ENV_CF_ACCOUNT_ID',
  'SECRET_ENV_CF_API_TOKEN',
  'SECRET_ENV_CF_SCRIPT_NAME',
  'SESSIONS',
  'SOS_SECRET',
  'SOS_TOKEN',
  'SQUAD',
  'STRIPE_SECRET_KEY',
  'STRIPE_WEBHOOK_SECRET',
  'SUPABASE_WEBHOOK_SECRET',
  'TASK_WORKFLOW',
  'TELEGRAM_BOT_TOKEN',
  'TELEGRAM_BRIDGE_URL',
  'TELEGRAM_CHAT_ID',
  'TENANT_SLUG',
  'TORIVERS_SECRET',
  'TYPESAFE_API_KEY',
  'VEC',
])

/** Dynamic-prefix names the worker derives at runtime (per-loop secrets LOOP_SECRET_<REF>_HOST; per-agent DISCORD_BOT_TOKEN_<AGENT>). */
export const RESERVED_BINDING_PREFIXES: readonly string[] = ['LOOP_SECRET_', 'DISCORD_BOT_TOKEN_']
