// mupot — Grok SEO & client commercial task intake template.
//
// Formats high-level client asks from Grok SEO, Slack, or Telegram into
// strict, capability-gated Mupot task contracts with verifiable done_when predicates.

import type { TaskPriority } from '../types'

export interface ClientIntakeRequest {
  clientSlug: string
  servicePackage: 'mcpwp-seo' | 'mcpwp-store' | 'mcpwp-content' | 'general-audit'
  title: string
  description: string
  targetUrl: string
  targetKeywords?: string[]
  priority?: TaskPriority
  requesterAgentId?: string
}

export interface StructuredClientTask {
  squadSlug: string
  title: string
  body: string
  doneWhen: string
  priority: TaskPriority
  externalSource: string
  suggestedGateOwner: string
}

export function formatClientIntakeTask(req: ClientIntakeRequest): StructuredClientTask {
  const squadSlug = `${req.clientSlug}-mcpwp`
  const priority: TaskPriority = req.priority ?? 'P1'
  const keywords = req.targetKeywords && req.targetKeywords.length > 0
    ? `\n- Target Keywords: ${req.targetKeywords.join(', ')}`
    : ''

  let doneWhen = ''
  switch (req.servicePackage) {
    case 'mcpwp-seo':
      doneWhen = `1. Fetch metadata for target page ${req.targetUrl} via wp_get_posts/wp_get_pages.
2. Update meta title and description with targeted keywords.
3. Fetch live HTML via HTTP and verify title and meta description tags match candidate.
4. Emit before/after diff in task result and receive gate clearance.`
      break
    case 'mcpwp-store':
      doneWhen = `1. Query target WooCommerce products on ${req.targetUrl}.
2. Apply requested price or stock updates via wc_update_product.
3. Verify updated fields on live WooCommerce endpoint.
4. Record product SKU summary in task result.`
      break
    case 'mcpwp-content':
      doneWhen = `1. Synthesize structured post with FAQ schema.
2. Create draft post in WordPress via wp_create_post.
3. Upload referenced media assets.
4. Client/operator approves draft, post transitions to published.`
      break
    case 'general-audit':
    default:
      doneWhen = `1. Run complete site health and SEO audit for ${req.targetUrl}.
2. Compile findings into structured recommendation list.
3. Record audit artifact in project evidence.`
      break
  }

  const body = `## Client Task Request: ${req.title}

- Client Tenant: \`${req.clientSlug}\`
- Service Package: \`${req.servicePackage}\`
- Target URL: ${req.targetUrl}${keywords}

### Overview & Instructions
${req.description.trim()}

---
*Generated by Grok SEO & Commercial Intake Pipeline*`

  return {
    squadSlug,
    title: `[${req.servicePackage.toUpperCase()}] ${req.title.trim()}`,
    body,
    doneWhen,
    priority,
    externalSource: `intake:${req.servicePackage}:${req.clientSlug}`,
    suggestedGateOwner: `gate:${req.clientSlug}-gate`,
  }
}
