// Generated build information module — DO NOT EDIT DIRECTLY.
// Generated by scripts/generate-build-info.mjs

export interface BuildInfo {
  commit: string | null
  clean: boolean
  builtAt: string | null
}

export const BUILD_INFO: BuildInfo = {
  commit: "43fbfb2c2b326aa0fa37dd09f7d59680073ea58b",
  clean: false,
  builtAt: "2026-08-07T23:12:15.649Z",
}
